Fix dynamic label regex parsing behaviour
czerwonk/junos_exporter pull request #176
Opened 2022-03-04 11:24 UTC by fstolba

This is supposed to fix !163. Basically introduces additional constraints for user supplied regexes and ensures that at least the default regex is loaded in all cases.

If there's any feedback for the code it's more than welcome since I'm a go novice.

2022-03-04 14:43 UTC, czerwonk requested changes

2022-03-04 14:43 UTC, czerwonk commented on junos_collector.go
> +			} else if !(*ignoreConfigTargets) && index <= len(cfg.Devices) {
Variable index has to be smaller than len(cfg.Devices) since it is zero based

2022-03-04 15:33 UTC, merged

2022-03-04 15:33 UTC, czerwonk commented
Thanks for contributing! 🙂

2022-04-27 13:33 UTC, qybl commented
Hi, I think this should warrant  a release as  0.9.14  is not usable with -config.ignore-targets=true without also disabling dynamic interface labels.